# @package _global_
defaults:
  - base@policy

  
policy:
  policy: maham
  use_ranking_pe: True
  param_sharing: False
  decoder_attn_mask: True
  ms_sparse_attn: True
  use_sku_attn: False
  ms_scores_tanh_clip: 2
  
env:
  name: msprp
  num_agents: null
  goal: min-max
  use_stay_token: True

model:
  eval_per_agent: True
  eval_multistep: True